package cn.vfinance.open.saas.web.dao;

import cn.vfinance.open.saas.web.model.AppInfo;

import java.util.List;

public interface AppInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_app_info
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_app_info
     *
     * @mbggenerated
     */
    int insert(AppInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_app_info
     *
     * @mbggenerated
     */
    int insertSelective(AppInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_app_info
     *
     * @mbggenerated
     */
    AppInfo selectByPrimaryKey(Integer id);

    List<AppInfo> selectBySelective(AppInfo appInfo);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_app_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(AppInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_app_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(AppInfo record);
}