package cn.vfinance.open.saas.web.dao;

import cn.vfinance.open.saas.web.model.ChannelWechat;

public interface ChannelWechatMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_channel_wechat
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_channel_wechat
     *
     * @mbggenerated
     */
    int insert(ChannelWechat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_channel_wechat
     *
     * @mbggenerated
     */
    int insertSelective(ChannelWechat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_channel_wechat
     *
     * @mbggenerated
     */
    ChannelWechat selectByPrimaryKey(Integer id);

    ChannelWechat selectByMerchantIdAndCode(ChannelWechat channelWechat);

    ChannelWechat selectByMchIdAndCode(ChannelWechat channelWechat);

    ChannelWechat selectBySelective(ChannelWechat channelWechat);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_channel_wechat
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ChannelWechat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_channel_wechat
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ChannelWechat record);

    int updateStatusByAppAndCode(ChannelWechat channelWechat);
}