package cn.vfinance.open.saas.web.dao;

import cn.vfinance.open.saas.web.model.MerchantInfo;

import java.util.List;

public interface MerchantInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_merchant_info
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_merchant_info
     *
     * @mbggenerated
     */
    int insert(MerchantInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_merchant_info
     *
     * @mbggenerated
     */
    int insertSelective(MerchantInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_merchant_info
     *
     * @mbggenerated
     */
    MerchantInfo selectByPrimaryKey(Integer id);

    List<MerchantInfo> selectBySelective(MerchantInfo merchantInfo);

    MerchantInfo selectByAppKey(String appKey);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_merchant_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(MerchantInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_merchant_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(MerchantInfo record);
}