package cn.vfinance.open.saas.web.dao;

import cn.vfinance.open.saas.web.model.MerchantRole;

import java.util.List;

public interface MerchantRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_channel_role
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_channel_role
     *
     * @mbggenerated
     */
    int insert(MerchantRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_channel_role
     *
     * @mbggenerated
     */
    int insertSelective(MerchantRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_channel_role
     *
     * @mbggenerated
     */
    MerchantRole selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_channel_role
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(MerchantRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_channel_role
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(MerchantRole record);

    List<MerchantRole> selectRoleByMerchant(Integer merchantId);

    List<MerchantRole> selectAllRoles();
}