package cn.vfinance.open.saas.web.model;

import java.util.Date;

public class AppInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_app_info.ID
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_app_info.APP_KEY
     *
     * @mbggenerated
     */
    private String appKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_app_info.APP_NAME
     *
     * @mbggenerated
     */
    private String appName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_app_info.APP_DESC
     *
     * @mbggenerated
     */
    private String appDesc;

    private String appSecret;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_app_info.MERCHANT_ID
     *
     * @mbggenerated
     */
    private Integer merchantId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_app_info.CREATE_TIME
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_app_info.STATUS
     *
     * @mbggenerated
     */
    private String status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_app_info.ID
     *
     * @return the value of t_app_info.ID
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_app_info.ID
     *
     * @param id the value for t_app_info.ID
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_app_info.APP_KEY
     *
     * @return the value of t_app_info.APP_KEY
     *
     * @mbggenerated
     */
    public String getAppKey() {
        return appKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_app_info.APP_KEY
     *
     * @param appKey the value for t_app_info.APP_KEY
     *
     * @mbggenerated
     */
    public void setAppKey(String appKey) {
        this.appKey = appKey == null ? null : appKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_app_info.APP_NAME
     *
     * @return the value of t_app_info.APP_NAME
     *
     * @mbggenerated
     */
    public String getAppName() {
        return appName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_app_info.APP_NAME
     *
     * @param appName the value for t_app_info.APP_NAME
     *
     * @mbggenerated
     */
    public void setAppName(String appName) {
        this.appName = appName == null ? null : appName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_app_info.APP_DESC
     *
     * @return the value of t_app_info.APP_DESC
     *
     * @mbggenerated
     */
    public String getAppDesc() {
        return appDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_app_info.APP_DESC
     *
     * @param appDesc the value for t_app_info.APP_DESC
     *
     * @mbggenerated
     */
    public void setAppDesc(String appDesc) {
        this.appDesc = appDesc == null ? null : appDesc.trim();
    }

    public String getAppSecret() {
        return appSecret;
    }

    public void setAppSecret(String appSecret) {
        this.appSecret = appSecret;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_app_info.MERCHANT_ID
     *
     * @return the value of t_app_info.MERCHANT_ID
     *
     * @mbggenerated
     */
    public Integer getMerchantId() {
        return merchantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_app_info.MERCHANT_ID
     *
     * @param merchantId the value for t_app_info.MERCHANT_ID
     *
     * @mbggenerated
     */
    public void setMerchantId(Integer merchantId) {
        this.merchantId = merchantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_app_info.CREATE_TIME
     *
     * @return the value of t_app_info.CREATE_TIME
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_app_info.CREATE_TIME
     *
     * @param createTime the value for t_app_info.CREATE_TIME
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_app_info.STATUS
     *
     * @return the value of t_app_info.STATUS
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_app_info.STATUS
     *
     * @param status the value for t_app_info.STATUS
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    @Override
    public String toString() {
        return "AppInfo{" +
                "id=" + id +
                ", appKey='" + appKey + '\'' +
                ", appName='" + appName + '\'' +
                ", appDesc='" + appDesc + '\'' +
                ", merchantId=" + merchantId +
                ", createTime=" + createTime +
                ", status='" + status + '\'' +
                '}';
    }
}