package cn.vfinance.open.saas.web.model;

import java.util.Date;

public class ChannelUnion {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_channel_union.ID
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_channel_union.MER_ID
     *
     * @mbggenerated
     */
    private String merId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_channel_union.NAME
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_channel_union.CODE
     *
     * @mbggenerated
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_channel_union.CERT_PASSWORD
     *
     * @mbggenerated
     */
    private String certPassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_channel_union.CERT_URL
     *
     * @mbggenerated
     */
    private String certUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_channel_union.MERCHANT_ID
     *
     * @mbggenerated
     */
    private Integer merchantId;

    private Integer appInfoId;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_channel_union.CREATE_TIME
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_channel_union.STATUS
     *
     * @mbggenerated
     */
    private String status;

    public ChannelUnion() {
    }

    public ChannelUnion(String code, Integer merchantId) {
        this.code = code;
        this.merchantId = merchantId;
    }

    public Integer getAppInfoId() {
        return appInfoId;
    }

    public void setAppInfoId(Integer appInfoId) {
        this.appInfoId = appInfoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_channel_union.ID
     *
     * @return the value of t_channel_union.ID
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_channel_union.ID
     *
     * @param id the value for t_channel_union.ID
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_channel_union.MER_ID
     *
     * @return the value of t_channel_union.MER_ID
     *
     * @mbggenerated
     */
    public String getMerId() {
        return merId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_channel_union.MER_ID
     *
     * @param merId the value for t_channel_union.MER_ID
     *
     * @mbggenerated
     */
    public void setMerId(String merId) {
        this.merId = merId == null ? null : merId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_channel_union.NAME
     *
     * @return the value of t_channel_union.NAME
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_channel_union.NAME
     *
     * @param name the value for t_channel_union.NAME
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_channel_union.CODE
     *
     * @return the value of t_channel_union.CODE
     *
     * @mbggenerated
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_channel_union.CODE
     *
     * @param code the value for t_channel_union.CODE
     *
     * @mbggenerated
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_channel_union.CERT_PASSWORD
     *
     * @return the value of t_channel_union.CERT_PASSWORD
     *
     * @mbggenerated
     */
    public String getCertPassword() {
        return certPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_channel_union.CERT_PASSWORD
     *
     * @param certPassword the value for t_channel_union.CERT_PASSWORD
     *
     * @mbggenerated
     */
    public void setCertPassword(String certPassword) {
        this.certPassword = certPassword == null ? null : certPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_channel_union.CERT_URL
     *
     * @return the value of t_channel_union.CERT_URL
     *
     * @mbggenerated
     */
    public String getCertUrl() {
        return certUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_channel_union.CERT_URL
     *
     * @param certUrl the value for t_channel_union.CERT_URL
     *
     * @mbggenerated
     */
    public void setCertUrl(String certUrl) {
        this.certUrl = certUrl == null ? null : certUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_channel_union.MERCHANT_ID
     *
     * @return the value of t_channel_union.MERCHANT_ID
     *
     * @mbggenerated
     */
    public Integer getMerchantId() {
        return merchantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_channel_union.MERCHANT_ID
     *
     * @param merchantId the value for t_channel_union.MERCHANT_ID
     *
     * @mbggenerated
     */
    public void setMerchantId(Integer merchantId) {
        this.merchantId = merchantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_channel_union.CREATE_TIME
     *
     * @return the value of t_channel_union.CREATE_TIME
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_channel_union.CREATE_TIME
     *
     * @param createTime the value for t_channel_union.CREATE_TIME
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_channel_union.STATUS
     *
     * @return the value of t_channel_union.STATUS
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_channel_union.STATUS
     *
     * @param status the value for t_channel_union.STATUS
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    @Override
    public String toString() {
        return "ChannelUnion{" +
                "id=" + id +
                ", merId='" + merId + '\'' +
                ", name='" + name + '\'' +
                ", code='" + code + '\'' +
                ", certPassword='" + certPassword + '\'' +
                ", certUrl='" + certUrl + '\'' +
                ", merchantId=" + merchantId +
                ", appInfoId=" + appInfoId +
                ", createTime=" + createTime +
                ", status='" + status + '\'' +
                '}';
    }
}