package cn.vfinance.open.saas.web.model;

import java.util.Date;

public class MerchantRoleMapping {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auth_merchant_role.ID
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auth_merchant_role.MERCHANT_ID
     *
     * @mbggenerated
     */
    private Integer merchantId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auth_merchant_role.ROLE_ID
     *
     * @mbggenerated
     */
    private Integer roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auth_merchant_role.CREATE_TIME
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auth_merchant_role.ID
     *
     * @return the value of auth_merchant_role.ID
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auth_merchant_role.ID
     *
     * @param id the value for auth_merchant_role.ID
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auth_merchant_role.MERCHANT_ID
     *
     * @return the value of auth_merchant_role.MERCHANT_ID
     *
     * @mbggenerated
     */
    public Integer getMerchantId() {
        return merchantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auth_merchant_role.MERCHANT_ID
     *
     * @param merchantId the value for auth_merchant_role.MERCHANT_ID
     *
     * @mbggenerated
     */
    public void setMerchantId(Integer merchantId) {
        this.merchantId = merchantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auth_merchant_role.ROLE_ID
     *
     * @return the value of auth_merchant_role.ROLE_ID
     *
     * @mbggenerated
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auth_merchant_role.ROLE_ID
     *
     * @param roleId the value for auth_merchant_role.ROLE_ID
     *
     * @mbggenerated
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auth_merchant_role.CREATE_TIME
     *
     * @return the value of auth_merchant_role.CREATE_TIME
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auth_merchant_role.CREATE_TIME
     *
     * @param createTime the value for auth_merchant_role.CREATE_TIME
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}