package cn.vfinance.open.saas.web.model;

import java.util.Date;
import java.util.List;

public class MerchantInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_merchant_info.ID
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_merchant_info.APP_KEY
     *
     * @mbggenerated
     */
    private String appKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_merchant_info.PASSWORD
     *
     * @mbggenerated
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_merchant_info.SALT
     *
     * @mbggenerated
     */
    private String salt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_merchant_info.NAME
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_merchant_info.DESCRIPTION
     *
     * @mbggenerated
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_merchant_info.PHONE
     *
     * @mbggenerated
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_merchant_info.EMAIL
     *
     * @mbggenerated
     */
    private String email;

    private Integer parentId;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_merchant_info.CREATE_TIME
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_merchant_info.STATUS
     *
     * @mbggenerated
     */
    private String status;

    private String usingStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_merchant_info.LOGIN_NUM
     *
     * @mbggenerated
     */
    private Integer loginNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_merchant_info.SOURCE
     *
     * @mbggenerated
     */
    private String source;

    private List<MerchantRole> merchantRoleList;

    public MerchantInfo() {
    }


    public MerchantInfo(String appKey) {
        this.appKey = appKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_merchant_info.ID
     *
     * @return the value of t_merchant_info.ID
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_merchant_info.ID
     *
     * @param id the value for t_merchant_info.ID
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_merchant_info.LOGIN_NUM
     *
     * @return the value of t_merchant_info.LOGIN_NUM
     * @mbggenerated
     */
    public Integer getLoginNum() {
        return loginNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_merchant_info.LOGIN_NUM
     *
     * @param loginNum the value for t_merchant_info.LOGIN_NUM
     * @mbggenerated
     */
    public void setLoginNum(Integer loginNum) {
        this.loginNum = loginNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_merchant_info.APP_KEY
     *
     * @return the value of t_merchant_info.APP_KEY
     * @mbggenerated
     */
    public String getAppKey() {
        return appKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_merchant_info.APP_KEY
     *
     * @param appKey the value for t_merchant_info.APP_KEY
     * @mbggenerated
     */
    public void setAppKey(String appKey) {
        this.appKey = appKey == null ? null : appKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_merchant_info.PASSWORD
     *
     * @return the value of t_merchant_info.PASSWORD
     * @mbggenerated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_merchant_info.PASSWORD
     *
     * @param password the value for t_merchant_info.PASSWORD
     * @mbggenerated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_merchant_info.SALT
     *
     * @return the value of t_merchant_info.SALT
     * @mbggenerated
     */
    public String getSalt() {
        return salt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_merchant_info.SALT
     *
     * @param salt the value for t_merchant_info.SALT
     * @mbggenerated
     */
    public void setSalt(String salt) {
        this.salt = salt == null ? null : salt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_merchant_info.NAME
     *
     * @return the value of t_merchant_info.NAME
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_merchant_info.NAME
     *
     * @param name the value for t_merchant_info.NAME
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_merchant_info.DESCRIPTION
     *
     * @return the value of t_merchant_info.DESCRIPTION
     * @mbggenerated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_merchant_info.DESCRIPTION
     *
     * @param description the value for t_merchant_info.DESCRIPTION
     * @mbggenerated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_merchant_info.PHONE
     *
     * @return the value of t_merchant_info.PHONE
     * @mbggenerated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_merchant_info.PHONE
     *
     * @param phone the value for t_merchant_info.PHONE
     * @mbggenerated
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_merchant_info.EMAIL
     *
     * @return the value of t_merchant_info.EMAIL
     * @mbggenerated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_merchant_info.EMAIL
     *
     * @param email the value for t_merchant_info.EMAIL
     * @mbggenerated
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    public Integer getParentId() {
        return parentId;
    }

    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_merchant_info.CREATE_TIME
     *
     * @return the value of t_merchant_info.CREATE_TIME
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_merchant_info.CREATE_TIME
     *
     * @param createTime the value for t_merchant_info.CREATE_TIME
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_merchant_info.STATUS
     *
     * @return the value of t_merchant_info.STATUS
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_merchant_info.STATUS
     *
     * @param status the value for t_merchant_info.STATUS
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    public String getUsingStatus() {
        return usingStatus;
    }

    public void setUsingStatus(String usingStatus) {
        this.usingStatus = usingStatus;
    }

    public String getSource() {
		return source;
	}

	public void setSource(String source) {
		this.source = source;
	}

    public List<MerchantRole> getMerchantRoleList() {
        return merchantRoleList;
    }

    public void setMerchantRoleList(List<MerchantRole> merchantRoleList) {
        this.merchantRoleList = merchantRoleList;
    }
}