package cn.vfinance.open.saas.web.model;

import java.util.Date;

public class MerchantPriviledge {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auth_channel_priviledge.ID
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auth_channel_priviledge.GROUP_CODE
     *
     * @mbggenerated
     */
    private String groupCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auth_channel_priviledge.GROUP_NAME
     *
     * @mbggenerated
     */
    private String groupName;

    private String groupIcon;


    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auth_channel_priviledge.PRI_CODE
     *
     * @mbggenerated
     */
    private String priCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auth_channel_priviledge.PRI_NAME
     *
     * @mbggenerated
     */
    private String priName;

    private String priIcon;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auth_channel_priviledge.CREATE_TIME
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auth_channel_priviledge.ID
     *
     * @return the value of auth_channel_priviledge.ID
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auth_channel_priviledge.ID
     *
     * @param id the value for auth_channel_priviledge.ID
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auth_channel_priviledge.GROUP_CODE
     *
     * @return the value of auth_channel_priviledge.GROUP_CODE
     *
     * @mbggenerated
     */
    public String getGroupCode() {
        return groupCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auth_channel_priviledge.GROUP_CODE
     *
     * @param groupCode the value for auth_channel_priviledge.GROUP_CODE
     *
     * @mbggenerated
     */
    public void setGroupCode(String groupCode) {
        this.groupCode = groupCode == null ? null : groupCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auth_channel_priviledge.GROUP_NAME
     *
     * @return the value of auth_channel_priviledge.GROUP_NAME
     *
     * @mbggenerated
     */
    public String getGroupName() {
        return groupName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auth_channel_priviledge.GROUP_NAME
     *
     * @param groupName the value for auth_channel_priviledge.GROUP_NAME
     *
     * @mbggenerated
     */
    public void setGroupName(String groupName) {
        this.groupName = groupName == null ? null : groupName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auth_channel_priviledge.PRI_CODE
     *
     * @return the value of auth_channel_priviledge.PRI_CODE
     *
     * @mbggenerated
     */
    public String getPriCode() {
        return priCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auth_channel_priviledge.PRI_CODE
     *
     * @param priCode the value for auth_channel_priviledge.PRI_CODE
     *
     * @mbggenerated
     */
    public void setPriCode(String priCode) {
        this.priCode = priCode == null ? null : priCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auth_channel_priviledge.PRI_NAME
     *
     * @return the value of auth_channel_priviledge.PRI_NAME
     *
     * @mbggenerated
     */
    public String getPriName() {
        return priName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auth_channel_priviledge.PRI_NAME
     *
     * @param priName the value for auth_channel_priviledge.PRI_NAME
     *
     * @mbggenerated
     */
    public void setPriName(String priName) {
        this.priName = priName == null ? null : priName.trim();
    }

    public String getGroupIcon() {
        return groupIcon;
    }

    public void setGroupIcon(String groupIcon) {
        this.groupIcon = groupIcon;
    }

    public String getPriIcon() {
        return priIcon;
    }

    public void setPriIcon(String priIcon) {
        this.priIcon = priIcon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auth_channel_priviledge.CREATE_TIME
     *
     * @return the value of auth_channel_priviledge.CREATE_TIME
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auth_channel_priviledge.CREATE_TIME
     *
     * @param createTime the value for auth_channel_priviledge.CREATE_TIME
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    @Override
    public boolean equals(Object o) {
        if(!(o instanceof MerchantPriviledge))return false;

        MerchantPriviledge that = (MerchantPriviledge) o;

        if(groupCode.equals(that.groupCode) &&
                groupName.equals(that.groupName)  &&
                priCode.equals(that.priCode)  &&
                priName.equals(that.priName)){
            return true;
        }
        return false;
    }

    @Override
    public int hashCode() {
        int result = id != null ? id.hashCode() : 0;
        result = 31 * result + (groupCode != null ? groupCode.hashCode() : 0);
        result = 31 * result + (groupName != null ? groupName.hashCode() : 0);
        result = 31 * result + (priCode != null ? priCode.hashCode() : 0);
        result = 31 * result + (priName != null ? priName.hashCode() : 0);
        result = 31 * result + (createTime != null ? createTime.hashCode() : 0);
        return result;
    }
}